# Generated by Django 5.2.7 on 2025-10-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entry_read_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-target_date']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', '未読（提出済み）'), ('READ', '既読')], default='SUBMITTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='grade',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
