# Generated by Django 5.2.7 on 2025-10-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-target_date'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AddField(
            model_name='entry',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'とてもわるい'), (2, 'わるい'), (3, 'ふつう'), (4, 'よい'), (5, 'とてもよい')], default=3, verbose_name='体調'),
        ),
        migrations.AddField(
            model_name='entry',
            name='mental',
            field=models.PositiveSmallIntegerField(choices=[(1, 'とても落ち込み気味'), (2, 'やや不調'), (3, 'ふつう'), (4, 'やや前向き'), (5, 'とても前向き')], default=3, verbose_name='メンタル'),
        ),
    ]
