# Generated by Django 5.2.7 on 2025-10-27 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_entry_options_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['student', '-target_date'], name='idx_entry_stu_date_desc'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['read_by'], name='idx_entry_read_by'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('student', 'target_date'), name='core_entry_student_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('condition__gte', 1), ('condition__lte', 5)), name='core_entry_condition_range'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('mental__gte', 1), ('mental__lte', 5)), name='core_entry_mental_range'),
        ),
    ]
